import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import NavigationBar from "@/components/navigation/NavigationBar";
import Providers from "./Providers";

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex flex-col min-h-[100dvh]">
            <div className="sticky top-0">
              <NavigationBar />
            </div>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
